### ISSUE TITLE
Error when trying to run the plugin

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-nnpa-reporting#3]
```
2024-03-19T09:53:57     WARNING    Traceback (most recent call last):
              File "C:\Users/rfairless/AppData/Roaming/QGIS/QGIS3\profiles\Editor/python/plugins\NnpaReporting\reporting_tool.py", line 42, in run
              self.openSettings()
              File "C:\Users/rfairless/AppData/Roaming/QGIS/QGIS3\profiles\Editor/python/plugins\NnpaReporting\reporting_tool.py", line 47, in openSettings
              dlg = SettingsDialog(self.iface)
              File "C:\Users/rfairless/AppData/Roaming/QGIS/QGIS3\profiles\Editor/python/plugins\NnpaReporting\settings_dialog.py", line 19, in __init__
              self.ui.layerComboBox.setFilters(Qgis.LayerFilter.PolygonLayer)
             AttributeError: type object 'Qgis' has no attribute 'LayerFilter'
             
```

**Comment by uclaros** [comment]
Should be fixed with 1723f40c
